### ISSUE TITLE
Blurred Images are square

### ISSUE THREAD

**Issue by iojcde** [braydoncoyer/braydoncoyer.dev#145]
Almost all of your images are round, but `next/image`'s blurred placeholders can't be styled very easily.
Have you considered putting a wrapper around the images? It'll add a bit of overhead, but It'll look much nicer.

I'm using the following snippet for my website:
```ts
import NextImage, { ImageProps } from 'next/image'

interface Props extends ImageProps {
  noRounded?: boolean
}
const Image = (props: Props) => {
  const isStatic = typeof props.src != `string`

  return (
    <div
      className={`${
        !props.noRounded && `rounded-md`
      } overflow-hidden inline-flex`}
    >
      <NextImage
        src={props.src}
        blurDataURL={!isStatic && (props.src as string)}
        placeholder="blur"
        {...props}
      />
    </div>
  )
}
export default Image
```

Though, I think most people won't notice this if they don't look closely.

**Comment by braydoncoyer** [comment]
This is an interesting idea - nice catch! 

Feel free to open a PR and implement the change. I'll probably get around to it one day, but other changes are taking my priority.
