### ISSUE TITLE
How to deploy it?

### ISSUE THREAD

**Issue by EaMarWi** [braydoncoyer/braydoncoyer.dev#165]
This blog is so beautiful. I really want to know how this is deployed? Is there a detailed tutorial? I really want to learn, but I don't know what the variables in the "env. example" file mean. Thank you very much!

**Comment by braydoncoyer** [comment]
I'll be releasing the Notion template that goes along with this open source portfolio. Once the template is available, deploying should be very straightforward.

**Comment by braydoncoyer** [comment]
Looping back around to inform you that I just released a stripped-down version of the article database I use for this repository. You should be able to duplicate, grab the database ID and use it in the repo!

https://www.notion.so/0d3e00c6bbe54231897b9fcbc7747f78?v=4d7f0006d9a144b5bd8b9251f2ec39cd
