### ISSUE TITLE
No Notion Template

### ISSUE THREAD

**Issue by tnv1r** [braydoncoyer/braydoncoyer.dev#167]
The following readme needs to have a "notion template" that you are using for your portfolio Replicating the notion database structure by reading repo code is tedious. 😢

**Comment by EaMarWi** [comment]
+1

**Comment by braydoncoyer** [comment]
I'll be releasing the Notion template that goes along with this open source portfolio. Once the template is available, deploying should be very straightforward.

**Comment by theapplegates** [comment]
That's exciting news. I have no idea how to "reverse engineer" a site using Notion. I'm only good enough to follow the instructions a theme/template/starter provides. Thanks in advance for your hard work.

**Comment by ByWaleed** [comment]
I was able to find some properties in `lib/types.ts`, which is as follows for an Article:

```JavaScript
export type Article = {
  title: string;
  tags?: string[];
  coverImage: string;
  summary: string;
  publishedDate?: any;
  lastUpdatedDate?: any;
};
```

Additionally, the `canonicalUrl` property is required for blog posts.

**Comment by animemandir** [comment]
> I'll be releasing the Notion template that goes along with this open source portfolio. Once the template is available, deploying should be very straightforward.

been a month sir, when.

**Comment by braydoncoyer** [comment]
Thanks for your patience. I duplicated the template I use with this repository and made a barebones version that you can add to your local system.

https://www.notion.so/0d3e00c6bbe54231897b9fcbc7747f78?v=4d7f0006d9a144b5bd8b9251f2ec39cd
