### ISSUE TITLE
Error in localy

### ISSUE THREAD

**Issue by thomassicaud** [braydoncoyer/braydoncoyer.dev#176]
Hello,

I tried to launch the project and once the dependencies are installed this is what I get? 

Could you help me please ?

![image](https://user-images.githubusercontent.com/72039072/181365256-bd720869-43a6-4279-a6d2-320f47710feb.png)

**Comment by braydoncoyer** [comment]
This is a url coming from the environment variables. You need to add a new environment variable in your `.env` file for both the NEXT_PUBLIC_SUPABASE_URL & NEXT_PUBLIC_SUPABASE_CLIENT_KEY. 


<img width="876" alt="image" src="https://user-images.githubusercontent.com/38799309/182039385-d1604858-98d8-4c33-8d69-f1b4dd957083.png">
