### ISSUE TITLE
How are you handling Notion images (and their expiring URLs)?

### ISSUE THREAD

**Issue by brandrsn** [braydoncoyer/braydoncoyer.dev#177]
Hey @braydoncoyer. Sweet project! I'm interested in Notion as a CMS too.
One question if you don't mind: how are you handling Notion images and the fact that their URLs expire after an hour?
I can see that the images on your site leverage Cloudinary, but can't see where that's been implemented (I'm a n00b).
Thanks!

**Comment by braydoncoyer** [comment]
I simply upload images to Cloudinary, snag the URL they give me and paste that into my Notion content! Since the URL points to the host, the blog picks up the URL and puts it in an `img` tag, so everything should work correctly!
