### ISSUE TITLE
[Bug]: Home page content not showing on initial request

### ISSUE THREAD

**Issue by rabraghib** [braydoncoyer/braydoncoyer.dev#178]
Page transition not firing when visiting the home page (which is rendered on the server side) the first time.

![Screenshot 2022-08-20 002505](https://user-images.githubusercontent.com/49442862/185718925-a59d111c-3642-4b3d-9e74-bfd3768beb52.png)

**Comment by braydoncoyer** [comment]
Try pulling the latest from v2.

There was an error in the next.config.js file that was keeping things from loading correctly. Please report back! :)

**Comment by rabraghib** [comment]
yes, it has been fixed 👍
