### ISSUE TITLE
Not able to deploy the website

### ISSUE THREAD

**Issue by SparshKesari** [braydoncoyer/braydoncoyer.dev#181]
Hey 👋🏻,

I am facing trouble in deploying the website via both Vercel and Netlify. The build is not giving any errors but the webpage is not able to render.

Can you help me, please?

**Comment by braydoncoyer** [comment]
I'm attempting to figure out why this is the issue. I will update this ticket when I make the fix!

**Comment by braydoncoyer** [comment]
Try pulling the latest from `v2`. 

There was an error in the next.config.js file that was keeping things from loading correctly. Please report back! :)

**Comment by SparshKesari** [comment]
Hey @braydoncoyer,

Everything works ✨🙌🏻.
