### ISSUE TITLE
Images are not rendered correctly when opening after a long time

### ISSUE THREAD

**Issue by SparshKesari** [braydoncoyer/braydoncoyer.dev#199]
Hey Braydon,
After opening after a long time, the images are not rendered correctly 

Can you please help

![image](https://user-images.githubusercontent.com/39815871/203473616-cf308d90-4408-4128-9143-39ecde9ae99b.png)

**Comment by braydoncoyer** [comment]
To clarify, the images load if you refresh? 

My guess is that the Notion API that serves the images became stale so a refresh is needed. This isn't a bug as much as it is how the Notion API works.

**Comment by braydoncoyer** [comment]
Going to close this issue since it's been open for over a year.
