### ISSUE TITLE
Extra Scrollbar in Navbar

### ISSUE THREAD

**Issue by Monik2002** [braydoncoyer/braydoncoyer.dev#217]
<img width="959" alt="image" src="https://github.com/braydoncoyer/braydoncoyer.dev/assets/87751450/829dbeab-e2df-4cc1-a85a-4c52220a0997">

Description:
There seems to be an extra scrollbar appearing in the navbar of the website. This additional scrollbar is causing unnecessary visual clutter and may impact the user experience negatively.

Steps to Reproduce:

Navigate to the website .
Scroll down to the navbar section.
Observe the presence of the extra scrollbar.

Expected Behavior:
The navbar should not display an extra scrollbar. Users should be able to navigate through the navbar items smoothly without encountering any unnecessary scrollbars.

Actual Behavior:
An additional scrollbar is visible within the navbar, which disrupts the layout and may confuse users.

Priority: Low

**Comment by braydoncoyer** [comment]
Thanks for the ticket! This will be resolved in my upcoming revamp this year, and since my current site is built with Framer, this repo will not update to fix the issue as it is. 

Thank you!
