### ISSUE TITLE
Add notion databases templates

### ISSUE THREAD

**Issue by andreacavagna01** [braydoncoyer/braydoncoyer.dev#223]
Hi Braydon!

Great job! This is the best personal portfolio I've seen so far! I love the Notion integration! Smart Idea. 

I would love to see in the readme also the other database templates to duplicate. 

I hope to contribute to the project in the next days

**Comment by braydoncoyer** [comment]
Hey @andreacavagna01 -- this project has kind of gone into maintenance mode, and the new version I'm publishing won't use Notion as my CMS. 

You should be able to look at the properties in the code and build out a table that is identical. I followed Jon's Egghead course to integrate Notion with Next. https://egghead.io/courses/build-static-pages-dynamically-using-next-js-and-the-notion-api-34849fc4
